<%@ Page Title="" Language="C#" AutoEventWireup="true" CodeBehind="Areas.aspx.cs" Inherits="Votacion_WebSite.Pages.Areas" %>

<link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet" />

<form runat="server">
    <asp:toolkitscriptmanager id="scriptManager" runat="server" enablescriptglobalization="true"
        enablescriptlocalization="true" enablepartialrendering="true" scriptmode="Release">
            </asp:toolkitscriptmanager>
    <asp:updatepanel id="UpdatePanel1" runat="server">        
        <ContentTemplate>
        <div class="col-md-12 text-center">
            Empresa: <asp:DropDownList ID="ddlCompany" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlCompany_SelectedIndexChanged">
            </asp:DropDownList>
        </div>
        <div class="col-md-12 text-center">            
            <asp:Label ID="lblError" ForeColor="Red" Visible="false" runat="server" />
            
                <asp:GridView ID="gvArea" runat="server" CellPadding="3" ForeColor="Black" GridLines="Vertical"
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False"
                    OnRowCancelingEdit="gvArea_RowCancelingEdit" OnRowDeleting="gvArea_RowDeleting"
                    OnRowEditing="gvArea_RowEditing" OnRowUpdated="gvArea_RowUpdated" OnRowUpdating="gvArea_RowUpdating"
                    BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" class="table">
                    <AlternatingRowStyle BackColor="#CCCCCC" />
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#808080" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#383838" />
                    <Columns>
                        <asp:TemplateField HeaderText="Nombre Empresa">
                            <EditItemTemplate>
                                <asp:Label ID="lbID_AREA" runat="server" Text='<%# Bind("ID_AREA") %>' Visible="false"></asp:Label>
                                <asp:TextBox runat="server" ID="tbNOMBRE_AREA" Text='<%# Bind("NOMBRE_AREA") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rftbNOMBRE_AREA" runat="server" ErrorMessage="Campo Requerido"
                                    ControlToValidate="tbNOMBRE_AREA" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbID_AREA" runat="server" Text='<%# Bind("ID_AREA") %>' Visible="false"></asp:Label>
                                <asp:Label ID="lbNOMBRE_AREA" runat="server" Text='<%# Bind("NOMBRE_AREA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>            
            <asp:Button ID="btAddArea" runat="server" Text="Agregar Area" OnClick="btAddArea_Click1" /><br />
            <div runat="server" id="dvaddArea" visible="false">
                <asp:Label ID="lbCompany" runat="server" Text="Empresa:"></asp:Label>
                <br />
                <asp:DropDownList ID="ddlCompany2" runat="server">
                </asp:DropDownList>
                <br />
                <asp:Label ID="lbNameArea" runat="server" Text="Nombre de Area:"></asp:Label>
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="tbNameArea" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="rfvtbNameArea" runat="server" ErrorMessage="*Campo requerido"
                    ControlToValidate="tbNameArea" ValidationGroup="save"></asp:RequiredFieldValidator>
                <br />
                <asp:Button ID="btAddAreaF" runat="server" Text="Guardar" ValidationGroup="save"
                    OnClick="btAddAreaF_Click" />
            </div>
        </div>
        </ContentTemplate>            
    </asp:updatepanel>
</form>
